=== thecorecity/cognitum/lib/schemas/language.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://thecore.city/cognitum/schemas/language.schema.json",
  "title": "Language pack file",
  "type": "object",
  "properties": {
    "_languagePack": {
      "type": "object",
      "title": "Language pack data",
      "description": "Information about current pack language, version and authors.",
      "properties": {
        "title": {
          "type": "string",
          "title": "Name",
          "description": "Pack or pack language name.",
          "default": "Language"
        },
        "dateLocale": {
          "type": "string",
          "title": "Date Locale",
          "description": "Date locale used in this language.",
          "default": "en-US"
        }
      },
      "required": [
        "title"
      ]
    },
    "bot": {
      "type": "object",
      "title": "Bot",
      "description": "All bot-related texts.",
      "patternProperties": {
        "^name$": {
          "type": "string",
          "title": "Bot name",
          "default": "Bot",
          "minLength": 1,
          "maxLength": 32
        },
        "^description$": {
          "type": "string",
          "title": "Bot description",
          "default": "Description",
          "minLength": 1,
          "maxLength": 500
        },
        "^[A-Za-z_]+$": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "name",
        "description"
      ]
    },
    "category": {
      "type": "object",
      "title": "Categories",
      "description": "Texts related to categories",
      "patternProperties": {
        "^[A-Za-z_]+$": {
          "type": "object",
          "title": "Category",
          "description": "Category entries.",
          "properties": {
            "title": {
              "type": "string",
              "title": "Category name",
              "default": "Category"
            }
          },
          "patternProperties": {
            "^[A-Za-z_]+$": {
              "type": [
                "string",
                "object"
              ]
            }
          },
          "required": [
            "title"
          ]
        }
      }
    },
    "command": {
      "type": "object",
      "title": "Commands",
      "description": "Texts related to commands.",
      "patternProperties": {
        "^[A-Za-z_]+$": {
          "type": "object",
          "title": "Command",
          "description": "Command entries.",
          "properties": {
            "title": {
              "type": "string",
              "title": "Command title"
            },
            "description": {
              "type": "string",
              "title": "Command description"
            }
          },
          "patternProperties": {
            "^[A-Za-z_]+$": {
              "type": [
                "string",
                "object"
              ]
            }
          },
          "required": [
            "title",
            "description"
          ]
        }
      }
    },
    "embed": {
      "type": "object",
      "title": "Embeds",
      "description": "Entries related to embeds.",
      "properties": {
        "errors": {
          "type": "object",
          "title": "Errors",
          "description": "Errors embeds fields.",
          "patternProperties": {
            "^[A-Za-z_]+$": {
              "type": "object",
              "title": "Error Embed",
              "description": "Entries related to current error embed",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Embed title"
                },
                "description": {
                  "type": "string",
                  "title": "Embed description"
                }
              },
              "patternProperties": {
                "^[A-Za-z_]+$": {
                  "type": [
                    "string",
                    "object"
                  ]
                }
              }
            }
          }
        },
        "tasks": {
          "type": "object",
          "title": "Tasks embeds entries",
          "description": "Object with entries for embed rendering for tasks",
          "patternProperties": {
            "^[A-Za-z_]+$": {
              "type": "object",
              "title": "Task embed",
              "description": "Embed for rendering task messages",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Embed title"
                },
                "description": {
                  "type": "string",
                  "title": "Embed description"
                }
              }
            }
          }
        },
        "logs": {
          "type": "object",
          "title": "Tasks embeds entries",
          "description": "Object with entries for embed rendering for log events",
          "patternProperties": {
            "^[A-Za-z_]+$": {
              "type": "object",
              "title": "Task embed",
              "description": "Embed for rendering task messages",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Embed title"
                },
                "description": {
                  "type": "string",
                  "title": "Embed description"
                }
              }
            }
          }
        }
      },
      "patternProperties": {
        "^[A-Za-z_]+$": {
          "type": "object",
          "title": "Embed",
          "description": "Embed entries",
          "properties": {
            "title": {
              "type": "string",
              "title": "Embed title"
            },
            "description": {
              "type": "string",
              "title": "Embed description"
            }
          },
          "patternProperties": {
            "^[A-Za-z_]+": {
              "type": [
                "string",
                "object"
              ]
            }
          },
          "required": [
            "title",
            "description"
          ]
        }
      }
    }
  },
  "required": [
    "_languagePack",
    "bot",
    "category",
    "command",
    "embed"
  ]
}

=== thecorecity/cognitum/lang/sk.json
{
  "$schema": "../lib/schemas/language.schema.json",
  "_languagePack": {
    "title": "Slovenský",
    "dateLocale": "sk-SK"
  },
  "bot": {
    "name": "Cognitum",
    "description": "Toto je malý Discord bot so zberom štatistík a užitočné funkcie vyrobené spoločenstvom The Core."
  },
  "category": {
    "basic": {
      "title": "Základné príkazy"
    }
  },
  "command": {
    "about": {
      "title": "O tomto bote",
      "description": "Zobrazuje informácie o tomto botovi."
    },
    "help": {
      "title": "Pomoc",
      "description": "Uvádza všetky dostupné príkazy a príklady použitia.",
      "commandsList": "Zoznam dostupných príkazov"
    }
  },
  "embed": {
    "default": {
      "title": "Vzorový názov",
      "description": "Vzorový popis."
    },
    "errors": {
      "default": {
        "title": "Došlo k chybe!",
        "description": "Nastala neočakávaná chyba! Skúste to znova neskôr a informujte nás o tomto probléme na [našom spolku Discord](https://discord.gg/SbNZQMV) a [v úložisku GitHub](https://github.com/thecorecity/cognitum/issues/new)."
      },
      "commandNotFound": {
        "title": "Príkaz `%commandName%` nenájdené!",
        "description": "Požadovaný príkaz nenájdené! Skúste zadaním `%prefix%help` získať úplný zoznam príkazov."
      }
    }
  }
}
